<div id="crewc" class="content">
	<div class="background-image"><img src="../img/nuansa/background.jpg" width="100%"></div>
	<div id="popup-bg">
		<div id="writeup">
			<div id="prod1c"><h3>Bernadette Natalia Pekerti</h3><hr class="belowtitle">
				<p>The year 2014 marks Bernadette’s third year in NUS’ Food Science and Technology programme and her seventh in Singapore. She has noticed that having left her home country for a relatively long time has brought about a paradoxical effect: the increasing surge of pride that she feels when recalling her home country, side-by-side with the subconscious dilution of her roots. Motivated by the drive to re-familiarise herself and fellow Indonesian diaspora to the rich Indonesian culture, as well as to introduce it to the people of the land that has taken care of her these past few years, Bernadette decided to channel the organizational skills she has gained while serving as a Student Council Executive Committee member both in her junior high school back in Bandung, Indonesia and later in Temasek Junior College, Singapore into producing a uniquely cultural musical that brings together her double inheritance from her two homes, NUS and Indonesia, in NUANSA’14: The Priyayi.</p></div>
			<div id="prod2c"><h3>Nurwidya Utami Jati</h3><hr class="belowtitle">
				<p>As an international student in NUS, Nurwidya has learned much about being in a diverse community in a global scale. Inspired by the understanding among different cultures and the tolerance as the result, she decided to take up the challenge to continue the effort of introducing the glimpse of myriads of culture and traditions from her own homeland, Indonesia, to the Singapore community. It is not only Nurwidya’s third year in NUS as an undergraduate student majoring Information System but also her third involvement in NUANSA. The exposure to the backstage environment in the previous NUANSAs and the performing related experience such as being a performer and student conductor in NUS Angklung Ensemble have aided her with basic knowledge to shape this production and hence encourage her to serve the NUANSA’14 family in fulfilling their wishes through one of their most incredible journeys in NUS.</p></div>
			<div id="secretaryc"><h3>Clara Nonie Susanto</h3><hr class="belowtitle">
				<p>Clara is a second year student at NUS Faculty of Science, studying Applied Mathematics. Her main area of interest is in event organising. She has an extensive experience as Executive Committee in both her CCAs in junior college, namely NJC Mathematics Society and NJC Angklung Group. She was also the Head of Organising Committee of Angklung Concert in 2012, one of the Committee Heads of Primary School Mathematics Competition, and also Honorary Secretary of the Secondary Mathematics Challenge in 2012. She is currently serving as Co-Lead in a project under NUS Entrepreneurship Society. Clara joins NUANSA in order to be a part of the community that promotes Indonesia’s rich history and culture.</p></div>
			<div id="treasurerc"><h3>Giovanni Victor Wicaksono</h3><hr class="belowtitle">
				<p>Giovanni Victor Wicaksono, affectionately known as Ivan, is in his third year studying Chemical and Biomolecular Engineering in NUS. Having been involved in the previous productions as Marketing Communications Executive in NUANSA ’12: Canting and Marketing Communications Director in NUANSA ’13: Dance of the Earth, Ivan thought his era in NUANSA was already over. Apparently, those two years have meant so much to him he found it impossible to let go. Ivan eventually decided to return for a final lap in NUANSA ’14: The Priyayi as the Treasurer. To him, NUANSA is more than just a student production; NUANSA is a home away from home, where he and fellow Indonesians in NUS can leave their marks on the community. Ivan takes pride in witnessing and contributing to NUANSA’s growth into what it is today: a beacon of light for anyone, anywhere, proud of his culture.</p></div>
			<div id="playc"><h3>Gregorius Ivaniddo</h3><hr class="belowtitle">
				<p>Having very little experience in performing arts (including acting as a rock in his primary school drama) especially in a musical theatre, does not discourage this third year Global Studies student to join this year NUANSA Production. Fortunately, his interest in Indonesia’s culture on top of his involvement in NUANSA’12: Canting, as a minion supporting cast, and NUANSA’ 13: Dance of the Earth, as an Artist Liaison Officer-cum- a supposedly-kind-but-is-being-misunderstood villain, have armed him with enough background to take up the challenging role of the Play Director of NUANSA’14: The Priyayi. For him, the show will be the first time he will stand behind the curtain and enjoy the fruit of his labor of almost 1 year of painful-but-enjoyable practices and planning, after two years he stood under the limelight in previous productions.</p></div>
			<div id="music1c"><h3>Elysia Cecilia Saputra</h3><hr class="belowtitle">
				<p>Having been exposed to music from a very young age, Elysia is no stranger to the world of performing arts. Hailing from a classical background, Elysia’s musical repertoire grew after joining the Raffles Girls’ School (Secondary) choir, where she learned vocal techniques and various genres of music, including sacral, folk and world music. She further developed her musicality by joining Raffles Jazz and NUS Jazz Band as a pianist in her junior college and university years. Currently in her final year as a Chemical Engineering major, NUANSA 2014: The Priyayi will be her last production as an undergraduate. Serving as the music director in this year’s installment, The Priyayi is Elysia’s second involvement in NUANSA and her first venture into music composition and songwriting.</p></div>
			<div id="music2c"><h3>Hans Jonathan Charis</h3><hr class="belowtitle">
				<p>Hans started learning the piano at a young age. A classical musician by trade - having gone along the ABRSM track in classical piano - Hans picked up jazz as he joined Raffles Jazz during his junior college years. Carrying on his passion for music, he now serves as president of NUS Jazz Band. An avid listener of a wide range of music and a lover of the performing arts in general, Hans is a fervent enthusiast of the musical theatre as well, and NUANSA gives him a valuable opportunity to work with a wonderful group of people in the particular form of art. NUANSA 2014: The Priyayi is Hans’ first involvement in a musical as music director and pianist - a new experience that has been a challenging but nonetheless enjoyable and inspiring one to him. Hans is currently a second-year student at NUS, reading History and Philosophy.</p></div>
			<div id="dance1c"><h3>Alvin Hadi Sumarlin</h3><hr class="belowtitle">
				<p>Alvin, or better known as Hadi, started dancing when he was in the second year of junior college. He joined the NUANSA family in his freshman year in 2013. Now, working together with his co-director, he strives to put together a spectacular performance for those who have supported and trusted him</p></div>
			<div id="dance2c"><h3>Shelvia Dwi Hotama</h3><hr class="belowtitle">
				<p>Shelvia is a year-two undergraduate in NUS, majoring in Industrial and Systems Engineering. At the age of four, Shelvia has been introduced to dancing through ballet classes and it has been her passion ever since. Currently, she is a member of NUS Dance Blast!, an NUS hiphop dance club, exploring a different genre of dance. Despite her experience, being a dance director in NUANSA is a challenge in itself for her. NUANSA’14 marks her debut as a choreographer for both traditional and contemporary dances. She hopes that her choreographies in NUANSA’14 are able to showcase the talents of NUANSA’14 dancers as well as the rich Indonesian culture to the world.</p></div>
			<div id="vocal1c"><h3>Michael L. Tanny</h3><hr class="belowtitle">
				<p>Michael is a final year student in NUS, currently studying Statistics and Applied Probability as well as Financial Mathematics as his minor. Being in a various choral groups for the past seven years, Michael has developed a passion in choral music and vocal production. He was the Bass section leader of the NUSChoir for the previous year and was in-charge in preparing the section to compete in the 8th World Choir Games in Riga, where the choir achieved three gold medals. Being a section leader in the group, Michael has honed his skills in teaching basics of vocal production. To him, NUANSA is a platform where he can explore different techniques in vocal productions, as well as a channel to contribute back to Indonesia, despite living and studying overseas. He hopes that with NUANSA, everyone will be inspired by our culture, unity in diversity.</p></div>
			<div id="vocal2c"><h3>Fenny Fong</h3><hr class="belowtitle">
				<p>After performing in NUANSA’13: Dance of the Earth as part of the main cast, Fenny shifts her involvement this year behind the scenes. Having developed a passion for singing since young, her prior experiences in the Anderson Secondary School and her church choir have deepened her love for singing. Over the years, she explored various singing styles such as choral, pop-rock, ballad and musicals. NUANSA empowers Fenny to channel her creative zeal and zest, not only in singing but also in writing and music. To her, the NUANSA experience has always been challenging, yet enjoyable. Her greatest joy this year has been in working together with various talented and amazing individuals in the team. In the process of vocal training for the cast, Fenny seeks to complement her fellow vocal director - Michael’s more technical approach by focusing on song interpretation. She currently reads Finance and Marketing at NUS Business School.</p></div>
			<div id="songwriterc"><h3>Andrea Marsha Lianto</h3><hr class="belowtitle">
				<p>From her past experiences as a member of TJC Guitar Ensemble and a tenor saxophonist in NUS Jazz Band, Andrea sought to discover a new creative interest, and subsequently fell in love with songwriting when she enrolled in an online Berklee course. Under the tutelage of Pat Pattison, Andrea cultivated her passion for rhyming and lyrics writing. Her love of the musical theatre eventually motivated her to make her debut as a songwriter in NUANSA ‘14: The Priyayi - her second involvement in a musical production after NUANSA ‘12: Canting. Songwriting continues to pose a challenge for this final year Quantitative Finance major, who is used to playing with numbers instead of words. A huge fan of Stephen Sondheim, Andrea is often inspired by his works. From him, Andrea learned that songwriting is not merely an art, but also a craft.</p></div>
			<div id="scriptwriterc"><h3>Adella Tifany</h3><hr class="belowtitle">
				<p>A Communication and New Media student, currently in her second year, Adella has found love in Indonesian literature since junior high school. She decided to join NUANSA as a scriptwriter because NUANSA might be the right platform to channel her love for Indonesian culture—in this case, literature and musical, something she has also been fond of since she was young (who doesn’t love Disney’s Lion King anyway). NUANSA’14: The Priyayi is her first scriptwriting experience. Though it is something very new to her, with the help of fellow scriptwriters, she learns a lot to grow more as a writer. She sincerely hopes everyone can enjoy the show and get a beautiful memory from it.</p></div>
			<div id="eah1c"><h3>Laura Novilia Gunarso</h3><hr class="belowtitle">
				<p>Laura is a third year student at NUS, studying Industrial and Systems Engineering as well as Management as her second major. Having more than ten years experience singing in various choirs, Laura is certainly no stranger to performing arts and she is currently a Soprano in The NUSChoir. She has also previously served the choir as the Vice-President and one of the soloists in various performances by The NUSChoir such as Christmas Concert, Annual Concert, and most recently, the 8th World Choir Games in Riga, Latvia where the choir went on to achieved three gold medals. To her, NUANSA is a way to contribute back to Indonesia despite living overseas. This motivates her to step up as External Affairs Executive Director and shapes her vision for the External Affairs Team, that is, to make NUANSA an inspiration for everyone to also cherish their culture wherever they are.</p></div>
			<div id="eah2c"><h3>Marvin Gowinatra</h3><hr class="belowtitle">
				<p>Having a passion for connecting to people and making new ties, Marvin – a Civil Engineering sophomore – devotes a great deal of energy and time into serving people in and out of the campus. His commitment in the University Scholars Programme community circle as a House Vice-Captain requires him to work closely with the University Scholars Club Management Committee in ensuring the welfare of the house members and representing their needs in the board of student governors. He is also actively serving the Indonesian community in NUS through many activities and instances; most importantly, he oversees and ensures the smooth running of a well-established community-based group made up by Indonesians in NUS who have a whole panoply of interests, such as the Arts, Sports, Social Work, Publication, Networking and Business Development. Away from the University, Marvin currently also serves as a Sunday school teacher because of his love for children. In spite of his already busy schedules, he still decided to join NUANSA for the second time this year as he hopes to expand his social circle and gain invaluable leadership and negotiating skills from this experience.</p></div>
			<div id="marketingc"><h3>Aditya Aulia Wibowo</h3><hr class="belowtitle">
				<p>Aditya is a third year economics major at NUS. An introvert by nature, Aditya challenged himself to take up the role of Marketing & Communication Director of NUANSA’14. To him, NUANSA has been an integral part of his university life, being the first project he chose to be involved in as an NUS student.  Having served as the first-violin in his hometown’s youth orchestra during his senior-high years, Aditya understands how much focus is needed to pull off an amazing and memorable show.  Hence, it is his mission to assure that the performers in NUANSA are able to practice without worrying about other issues, especially financial matters. Aditya believes that NUANSA is an invaluable platform for Indonesian students to discover and hone their talents and leadership skills. It is his aspiration to see NUANSA, together with its committees, reach a greater height.</p></div>
			<div id="corporatec"><h3>Yuli Samantha</h3><hr class="belowtitle">
				<p>Yuli is a penultimate year student in Industrial and Systems Engineering. Having been in NUANSA’13 as Wardrobe Head, now she is involved again in NUANSA’14 as Corporate Relations Head. She enjoys trying out different activities in NUS like NUS Rovers and Jazztitude and currently serves as a Student Ambassador for NUS Office of Corporate Relations. Having been part of NUANSA for two consecutive years has presented her with many opportunities to grow and improve her communication and organizational skills. However, above all, she is delighted to be part of the mission to introduce and preserve our mesmerizing culture to the international community.</p></div>
			<div id="creativec"><h3>Aditya Hendraatmaja</h3><hr class="belowtitle">
				<p>Aditya is a second year Electrical Engineering student at NUS. Passionate in design, he also acts as the Head of Publicity at NUSSU Committee for Information Technology. He develops interest in Arts since secondary school, where he was the President of Temasek Secondary School Choir. At Junior College, he was introduced to design works and videography while serving as a student councilor. Now, still continuing to explore various works of arts by learning German language and cinematography, NUANSA has become one of his biggest projects in NUS. He was inspired by the strong Indonesian culture within NUANSA shown by his seniors. Through his creative ideas, he wishes to further spread the knowledge of Indonesia to his peers – Indonesian and foreigners alike.</p></div>
			<div id="ticketingc"><h3>Gede Agus Aswamada</h3><hr class="belowtitle">
				<p>Gede is a third year student at NUS, studying Civil Engineering. Gede has a wide interest ranging from sports to arts. He took charge of Indonesian Students Futsal Team in 2013 and was part of the winning team in LIGA PPIS 2012. Besides being actively involved in sporting activities, Gede is also a member in NUS Angklung Ensemble (NUSAE) and he currently takes up the position of Vice President for NUSAE’14. To him, NUANSA is a family and a place to facilitate his passion in contributing to society, especially to Indonesians.  He envisions NUANSA as a medium to preserve and promote his hometown’s culture to people in Singapore. He also hopes that by being a part of NUANSA, he can help facilitate Indonesians’ talents and inspire everyone who watches NUANSA.</p></div>
			<div id="ph1c"><h3>Theodore William Salim</h3><hr class="belowtitle">
				<p>Theodore is a final year Electrical Engineering student at NUS. Albeit having virtually no interest in performing arts and preferring being outdoors, Theodore decided to join NUANSA in 2012. After all, NUANSA is one way to contribute back to the beautiful country that he loves so much. Nevertheless, he never enjoys performing on a stage and thus first joined as a Sets and Props member, where he found his passion in being a backstage production crew; and then as the Head of Sets and Props in 2013. Still dreaming to bring NUANSA to a higher level, he joins again this year as a Production Team Executive Director. He truly believes that being a backstage crew is not just about creating something out of nothing, but also about building a legacy and turning dreams into reality.</p></div>
			<div id="ph2c"><h3>Albert Kurniawan</h3><hr class="belowtitle">
				<p>Albert is a fourth year Business Administration student in NUS specializing in Finance and Supply Chain Management. Having joined NUANSA’12 committee as Logistic member out of curiosity, he found the satisfaction being involved in a musical production. Albert consider production as a vital part of a musical production and found that it interest him the most. Therefore, he stepped up as the head of Logistic Division for NUANSA’13 the next year. This year he joined NUANSA again as the Production Team Executive Director for NUANSA’14. To him, NUANSA is a great achievement by the Indonesian students in NUS in which the Indonesians can be proud of. More importantly, NUANSA serves as a medium to introduce Indonesia vast culture to Singapore community.</p></div>
			<div id="stagec"><h3>Dominico Adrian Sundjaja</h3><hr class="belowtitle">
				<p>Dominico is a second year student majoring in Mechanical Engineering. He enjoys performing arts and has the chance to become the part of it in NUS. He was a member of NUS Guitar Ensemble (GENUS) and participated in the NUS Arts Festival 2014. In NUANSA, he was first involved as the assistant stage manager of NUANSA’13: Dance of the Earth. Feeling challenged to contribute more, he joined NUANSA’14 and stepped up to become the stage manager. To him, NUANSA is a place where he can thrive as a person and a place where he can contribute to his beloved country, Indonesia.</p></div>
			<div id="lightingc"><h3>Angelita Sasmita</h3><hr class="belowtitle">
				<p>A second year undergraduate of NUS, Angelita pursues a major in Industrial & Systems Engineering. Her passion in theatrical production started from her Junior College days, when she was an Assistant Lighting Manager for Saint Andrew’s Junior College Drama Club. During that time, she was involved in two annual public productions, entitled ‘Diary of a Mad Woman’ and ‘Three Children’. She also participated in Singapore Youth Festival 2012. During her freshman year in NUS, she joined the Lighting Division of NUANSA’13 Dance of the Earth. She viewed NUANSA as a platform to challenge herself creatively and promote Indonesia’s cultural tradition to the international public.</p></div>
			<div id="setsc"><h3>Kiki Indriani</h3><hr class="belowtitle">
				<p>Kiki is currently a second year student in NUS, pursuing a degree in civil engineering. She is a girl of many interests, including arts and crafts. Wishing to contribute something to Indonesian community in NUS as well as having a platform to express herself through arts in Singapore, she decided to join NUANSA’13 as sets and props member. NUANSA’13 marks her first involvement in a cultural production. The joy and fulfilment after the success of her first show inspired her to take up a higher position in the production. She then decided to take the role of sets and props head in this year’s performance.</p></div>
			<div id="wardrobec"><h3>Cynthia Rebecca</h3><hr class="belowtitle">
				<p>Cynthia is a second year student in NUS, pursuing Economics as her major. Her first involvement in theatrical production was during her Junior College days, with a play titled Diary of a Mad Woman, which enticed her to learn more about backstage roles. In her first year in NUS, she served as the Head of Wardrobe in Sheares Production’s hilarious comedy, Don’t Dress for Dinner. She then discovered her interest in handling the aesthetical aspects of staged plays, especially for the performers. To her, NUANSA is the perfect platform to dwelve deeper into Indonesian culture, especially when many of us are getting increasingly detached from our beloved country.</p></div>
			<div id="artistc"><h3>Christian Hadi Wijaya</h3><hr class="belowtitle">
				<p>Christian is a second year student at NUS, studying Industrial and Systems Engineering. His main areas of interest are performing arts and organising projects. After his experience as the Bass Section Leader of the pioneering batch of SJI Vocal Ensemble, he is now part of Resonance, the a capella CCA of NUS. In addition, he was also the Project Coordinator of Temasek Junior College Students’ Council, Special Project Head of the NUS Indonesian Catholic Community and the Programme Coordinator of L-derly Befrienders, a Regular Volunteering Programme under the NUS Community Service Club. He is currently serving as the Vice-Chairperson of the aforementioned volunteering programme. Christian joins NUANSA because he is keen on preserving and promoting Indonesian culture. He also wants to help to bring NUANSA to greater height.</p></div>
			<div id="soundc"><h3>Audri Gideon Hasibuan</h3><hr class="belowtitle">
				<p>Audri has been a student in NUS for two years, majoring in Chemical Engineering. First joining a performing art group in 2011, he is now the Treasurer of NUS Guitar Ensemble and is currently playing the Prime guitar as well as various percussion instruments. Welcomed in the NUANSA family in 2013, it was a new experience for him as it is his first musical, and first involvement in a performance as a backstage crew. Living far away from home for around 6 years, NUANSA is Audri's way of expressing his love for Indonesian culture.</p></div>
			<div id="logisticsc"><h3>Wiliam Salim</h3><hr class="belowtitle">
				<p>After watching NUANSA’13: Dance of The Earth last year when he was a freshman, it took him less than five seconds to decide that he wanted to be part of NUANSA and look, it is where he is now,  part of the production team of NUANSA’14. Taking on the role of Logistics Head in his first year in NUANSA is certainly not an easy job. With minimum experience and knowledge on cultural production, it is a very demanding position to be in, where his people management, time management and job delegation skills are tested. Not to mention, the need to juggle between NUANSA, academic and other commitments. However, despite the crazy life-draining experience, he can assure you it is worth more than what you give to NUANSA: Friendships, skills and memories that will last through lifetime. </p></div>
			<div id="welfarec"><h3>Aileen Supriyadi</h3><hr class="belowtitle">
				<p>Aileen is a second year student at NUS, studying Food Science and Technology. Experienced in organizing several events for the past few years, NUANSA becomes a new experience to her as it marks her first time to be involved in a major art event, more importantly a musical production. To her, through NUANSA, she is able to showcase Indonesia’s traditional cultural heritage, her pride. NUANSA becomes a chance to her to contribute back to Indonesia by promoting Indonesian cultures to international audiences.</p></div>
		</div>
		<div id="close">Close</div>
	</div>
	<div id="crewlink" class="namelist">
		<ul>
			<li id="admin">Administration Team</li>
			<li id="artistic">Artistic Team</li>
			<li id="ea">External Affairs Team</li>
			<li id="production">Production Team</li>
		</ul>
	</div>
	<div id="crews" class="main-content">
		<div id="adminc" class="tab-content">
			<table class="crew-content">
				<tr><td colspan="2" class="team-name">Administration Team</td></tr>
				<tr><td colspan="2"><span class="job-pos">Producers</span></td></tr>
				<tr><td><div id="prod1" class="crew-photo"><img src="img/crew/prod1.jpg"></div></td><td><div id="prod2" class="crew-photo"><img src="img/crew/prod2.jpg"></div></td></tr>
				<tr><td>Bernadette Natalia Pekerti</td><td>Nurwidya Utami Jati</td></tr>
				<tr class="space"><td colspan="2"></td></tr>
				<tr><td><span class="job-pos">Secretary</span></td><td><span class="job-pos">Treasurer</span></td></tr>
				<tr><td><div id="secretary" class="crew-photo"><img src="img/crew/secretary.jpg"></div></td><td><div id="treasurer" class="crew-photo"><img src="img/crew/treasurer.jpg"></div></td></tr>
				<tr><td>Clara Nonie Susanto</td><td>Giovanni Victor Wicaksono</td></tr>
			</table>
		</div>
		<div id="artisticc" class="tab-content">
			<table class="crew-content">
				<tr><td colspan="4" class="team-name">Artistic Team</td></tr>
				<tr><td colspan="4"><span class="job-pos">Play Director</span></td></tr>
				<tr><td colspan="4"><div id="play" class="crew-photo"><img src="img/crew/play.jpg"></div></td></tr>
				<tr><td colspan="4">Gregorius Ivaniddo</td></tr>
				<tr class="space"><td colspan="4"></td></tr>
				<tr><td colspan="2"><span class="job-pos">Music Directors</span></td><td colspan="2"><span class="job-pos">Dance Directors</span></td></tr>
				<tr><td><div id="music1" class="crew-photo"><img src="img/crew/music1.jpg"></div></td><td><div id="music2" class="crew-photo"><img src="img/crew/music2.jpg"></div></td><td><div id="dance1" class="crew-photo"><img src="img/crew/dance1.jpg"></div></td><td><div id="dance2" class="crew-photo"><img src="img/crew/dance2.jpg"></div></td></tr>
				<tr><td>Elysia Cecilia Saputra</td><td>Hans Jonathan Charis</td><td>Alvin Hadi Sumarlin</td><td>Shelvia Dwi Hotama</td></tr>
				<tr class="space"><td colspan="4"></td></tr>
				<tr><td colspan="2"><span class="job-pos">Vocal Directors</span></td><td><span class="job-pos">Songwriter</span></td><td><span class="job-pos">Scriptwriter</span></td></tr>
				<tr><td><div id="vocal1" class="crew-photo"><img src="img/crew/vocal1.jpg"></div></td><td><div id="vocal2" class="crew-photo"><img src="img/crew/vocal2.jpg"></div></td><td><div id="songwriter" class="crew-photo"><img src="img/crew/songwriter.jpg"></div></td><td><div id="scriptwriter" class="crew-photo"><img src="img/crew/scriptwriter.jpg"></div></td></tr>
				<tr><td>Michael Linardi Tanny</td><td>Fenny</td><td>Andrea Marsha Lianto</td><td>Adella Tiffany</td></tr>
			</table>
		</div>
		<div id="eac" class="tab-content">
			<table class="crew-content">
				<tr><td colspan="4" class="team-name">External Affairs Team</td></tr>
				<tr><td></td><td><span class="job-pos">Executive Director</span></td><td><span class="job-pos">Assistant Executive Director</span></td><td></td></tr>
				<tr><td></td><td><div id="eah1" class="crew-photo"><img src="img/crew/eah1.jpg"></div></td><td><div id="eah2" class="crew-photo"><img src="img/crew/eah2.jpg"></div></td><td></td></tr>
				<tr><td></td><td>Laura Novilia Gunarso</td><td>Marvin Gowinatra</td><td></td></tr>
				<tr class="space"><td colspan="6"></td></tr>
				<tr><td><span class="job-pos">Marketing Communications</span></td><td><span class="job-pos">Corporate Relations</span></td><td><span class="job-pos">Creative & Advertising</span></td><td><span class="job-pos">Sales & Ticketing</span></td></tr>
				<tr><td><div id="marketing" class="crew-photo"><img src="img/crew/marketing.jpg"></div></td><td><div id="corporate" class="crew-photo"><img src="img/crew/corporate.jpg"></div></td><td><div id="creative" class="crew-photo"><img src="img/crew/creative.jpg"></div></td><td><div id="ticketing" class="crew-photo"><img src="img/crew/ticketing.jpg"></div></td></tr>
				<tr><td>Aditya Aulia Wibowo</td><td>Yuli Samantha</td><td>Aditya Hendraatmaja</td><td>Gede Agus Aswamada</td></tr>
			</table>
		</div>
		<div id="productionc" class="tab-content">
			<table class="crew-content">
				<tr><td colspan="4" class="team-name">Production Team</td></tr>
				<tr><td colspan="4"><span class="job-pos">Executive Directors</span></td></tr>
				<tr><td></td><td><div id="ph1" class="crew-photo"><img src="img/crew/ph1.jpg"></div></td><td><div id="ph2" class="crew-photo"><img src="img/crew/ph2.jpg"></div></td><td></td></tr>
				<tr><td></td><td>Theodore William Salim</td><td>Albert Kurniawan</td><td></td></tr>
				<tr class="space"><td colspan="4"></td></tr>
				<tr><td><span class="job-pos">Stage Manager</span></td><td><span class="job-pos">Lighting</span></td><td><span class="job-pos">Sets & Props</span></td><td><span class="job-pos">Wardrobe</span></td></tr>
				<tr><td><div id="stage" class="crew-photo"><img src="img/crew/stage.jpg"></div></td><td><div id="lighting" class="crew-photo"><img src="img/crew/lighting.jpg"></div></td><td><div id="sets" class="crew-photo"><img src="img/crew/sets.jpg"></div></td><td><div id="wardrobe" class="crew-photo"><img src="img/crew/wardrobe.jpg"></div></td></tr>
				<tr><td>Dominico Adrian Sundjaja</td><td>Angelita Sasmita</td><td>Kiki Indriani</td><td>Cynthia Rebecca</td></tr>
				<tr class="space"><td colspan="4"></td></tr>
				<tr><td><span class="job-pos">Artist Liaison</span></td><td><span class="job-pos">Sound Engineer</span></td><td><span class="job-pos">Logistics</span></td><td><span class="job-pos">Welfare</span></td></tr>
				<tr><td><div id="artist" class="crew-photo"><img src="img/crew/artist.jpg"></div></td><td><div id="sound" class="crew-photo"><img src="img/crew/sound.jpg"></div></td><td><div id="logistics" class="crew-photo"><img src="img/crew/logistics.jpg"></div></td><td><div id="welfare" class="crew-photo"><img src="img/crew/welfare.jpg"></div></td></tr>
				<tr><td>Christian Hadi Wijaya</td><td>Audri Gideon Hasibuan</td><td>Wiliam Salim</td><td>Aileen Supriyadi</td></tr>
			</table>
		</div>
	</div>
</div>